#!/usr/bin/env bash
# Write a Bash script that displays To infinity and beyond indefinitely.
# In between each iteration of the loop, add a sleep 2

count=0
while [ $count -eq 0 ]
do
	echo "To infinity and beyond"
	sleep 2
done
exit 0
